title:            慈晖学堂-Oh My Class！
tagline:          A beautiful theme.
description:      Describe your website.
canonical: http://bit.ly/cihuixuetang_OhMyClass

# Owner/author information
owner:
  name:           慈晖学堂
  #avatar:         avatar.png
  #bio:            "Aesthete & Athlete"
  email:          johor.laishi@gmail.com
  #twitter:        twnsndco
  #github:         coletownsend
  #instagram:      ctrunsthis
  #dribbble:       coletownsend
  disqus:         cihuixuetang
  #location:       "Buffalo, NY"
  # Plug in your disqus shortname!

tools:
  standards:      "HTML, SCSS, Jekyll"
  software:       "git"

# Open Graph customization
opengraph:
  locale:           en_US

# Links to include in top navigation
# For external links add external: true
links:
  - title: 关于我们
    url: /about
  #- title: Github
  #  url: https://github.com/ColeTownsend/Balzac-for-Jekyll
  #  external: true
  - title: 联系我们
    url: /contact

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Asia/Kuala_Lumpur
future:      true
highlighter: rouge
markdown:    kramdown

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

  coderay:
    coderay_line_numbers:
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

sass:
    style: :compressed

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp"]
comments: true